// Generated by CoffeeScript 1.6.3
(function($) {
  var createBox, root;
  root = null;
  $.fn.ppedit = function() {
    var createBoxbutton;
    root = this.addClass("ppedit-container");
    createBoxbutton = $("<button>Create Box</button>");
    this.append(createBoxbutton);
    createBoxbutton.click(function() {
      return createBox();
    });
    return this;
  };
  return createBox = function(options) {
    var newBox, settings;
    settings = $.extend({
      left: '50px',
      top: '50px',
      width: '100px',
      height: '200px'
    }, options);
    newBox = $('<div class="ppedit-box"><div>').css(settings);
    return root.append(newBox);
  };
})(jQuery);
