// Generated by CoffeeScript 1.6.3
(function() {
  var ppeditDescribe;

  ppeditDescribe = function(suitDescription, specDefinitions) {
    return describe('', function() {
      beforeEach(function() {
        return $(".editor").ppedit();
      });
      afterEach(function() {
        return $('.editor').children().remove();
      });
      return describe(suitDescription, specDefinitions);
    });
  };

  ppeditDescribe("A ppedit Jasmine test template", function() {
    return it("contains spec with an expectation", function() {
      return expect(true).toBe(true);
    });
  });

  ppeditDescribe("A test for issue CAP-14 : As a user, I want to reposition elements visible on my work area", function() {
    it("adds a box on add element button click", function() {
      $(".addElementBtn").click();
      return expect($(".editor").find('.ppedit-box')).toHaveLength(1);
    });
    return it("does a box on add element button click", function() {
      $(".addElementBtn").click();
      return expect($(".editor").find('.ppedit-box')).toHaveLength(1);
    });
  });

}).call(this);
